apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  addresses:
    - 192.168.50.126/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private
  namespace: metallb-system
spec:
  addresses:
    - 192.168.50.254/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - public
    - private
