apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../overlays/kubeadm/clusterissuer-step-int-ca.yaml
  - ../overlays/kubeadm/clusterissuer-le-prod.yaml
  - ../overlays/kubeadm/clusterissuer-le-staging.yaml
  - ../overlays/kubeadm/clusterissuer-selfsigned.yaml
