apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer-step-int-ca.yaml
  - clusterissuer-le-prod.yaml
  - clusterissuer-le-staging.yaml
  - clusterissuer-selfsigned.yaml
