apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts/cert-manager
    version: 1.19.3
    releaseName: external-dns
    namespace: external-dns-internal
    valuesInline:
      crds.enabled: "true"

resources:
  - issuers/overlays/kubeadm