server:
  ingress:
    enabled: true
    ingressClassName: traefik-internal
    hostname: argocd.int.blackcircuit.ca
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-blackcircuit-staging
    tls: true

